# ── Profil actif ──────────────────────────────────────────────────────────────
spring.profiles.active=dev

# ── Nom de l'application ───────────────────────────────────────────────────────
spring.application.name=cowork-flex-backend
server.port=8080

# ── JPA ───────────────────────────────────────────────────────────────────────
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
