# ── PostgreSQL (production) ───────────────────────────────────────────────────
spring.datasource.url=jdbc:postgresql://localhost:5432/coworkflexdb
spring.datasource.username=postgres
spring.datasource.password=votre_mot_de_passe

spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false
